typography_spectrum: 0.5154134910553694
color:
  brandStrength: 0.9840874471701682
  lightness: 0.1958461245521903
  saturation: 0.10906764748506248
  rhythmicContrast: 0.307705030310899
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
layout_spectrum: 0.4251432807650417
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1a228ea-8618-411d-af36-c31a352e122a.svg
name: aaa-fo-test
navigation:
  - name: Contact
    id: 988b4968-6e9b-43cf-8a25-6452d37fcf04
    type: content
  - name: internal thing
    id: 5c742b2a-d581-4885-ac3e-83c90f395fa1
    type: content
  - name: manual link home
    url: 'https://thegrid.ai/aaa-fo-test/'
    type: external
  - name: ed-userhtml test
    id: 6f1490b5-b41b-4ec8-a905-cf59f849d876
    type: content
  - name: starred post with cta
    id: 5e689cba-2211-48fd-80de-2717071563c0
    type: content
title: fo-test
content: []
description: a gridster tests gridstuff
purpose: []
