typography_spectrum: 0.3143849026101946
color:
  brandStrength: 0.03904332546720115
  lightness: 0.17342713676780316
  saturation: 0.8200638470657649
  rhythmicContrast: 0.19308781540906517
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.1454982660965312
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1a228ea-8618-411d-af36-c31a352e122a.svg
name: aaa-fo-test
navigation:
  - name: Contact
    id: 988b4968-6e9b-43cf-8a25-6452d37fcf04
    type: content
  - name: internal thing
    id: 5c742b2a-d581-4885-ac3e-83c90f395fa1
    type: content
  - name: manual link home
    url: 'https://thegrid.ai/aaa-fo-test/'
    type: external
  - name: starred post with cta
    id: 5e689cba-2211-48fd-80de-2717071563c0
    type: content
title: fo-test
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fw_MSFkZHNi4%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dw_MSFkZHNi4&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fw_MSFkZHNi4%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Felix Colgrave
          url: 'https://www.youtube.com/user/MasterAardvark'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - double king
        - double
        - king
        - animation
        - regicide
        - crowns
        - felix colgrave
        - felix
        - colgrave
        - cartoon
        - royalty
      description: >-
        A film about love and regicide. Made by myself over 2 years. If you
        liked it, consider buying some Double King merchandise! Including
        limited edition signed risograph prints, at felixcolgrave.com/shop
        --------------------------------- felixcolgrave.com
        felixcolgrave.tumblr.com twitter.com/felixcolgrave
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=w_MSFkZHNi4&feature=applinks'
          namespace: ai
          type: ios
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=w_MSFkZHNi4&feature=applinks'
          namespace: ai
          type: android
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=w_MSFkZHNi4&feature=applinks'
          namespace: ai
          type: web
        - url: 'vnd.youtube://www.youtube.com/watch?v=w_MSFkZHNi4&feature=applinks'
          type: ipad
          namespace: twitter
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=w_MSFkZHNi4&feature=applinks'
          type: iphone
          namespace: twitter
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=w_MSFkZHNi4'
          type: googleplay
          namespace: twitter
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=w_MSFkZHNi4
          type: android
          namespace: google
          package: com.google.android.youtube
        - path: vnd.youtube/www.youtube.com/watch?v=w_MSFkZHNi4
          type: ios
          namespace: google
          package: '544007664'
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://www.youtube.com/watch?v=w_MSFkZHNi4'
      title: DOUBLE KING
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: a gridster tests gridstuff
purpose:
  - type: internal
    label: Ff
    item: 62c6fa65-46df-4a4c-894c-e194b86a3b24
