typography_spectrum: 0.8577892524088816
color:
  brandStrength: 0.6612298715439173
  lightness: 0.7091567047488977
  saturation: 0.6290894739807463
  rhythmicContrast: 0.17694657978832282
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.4946329683587324
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1a228ea-8618-411d-af36-c31a352e122a.svg
name: aaa-fo-test
navigation:
  - name: Contact
    id: 988b4968-6e9b-43cf-8a25-6452d37fcf04
    type: content
  - name: internal thing
    id: 5c742b2a-d581-4885-ac3e-83c90f395fa1
    type: content
  - name: manual link home
    url: 'https://thegrid.ai/aaa-fo-test/'
    type: external
  - name: starred post with cta
    id: 5e689cba-2211-48fd-80de-2717071563c0
    type: content
title: fo-test
content: []
description: a gridster tests gridstuff
purpose: []
