typography_spectrum: 0.13088201600154586
color:
  brandStrength: 0.1693532195660553
  lightness: 0.4460615896842083
  saturation: 0.23378968956705073
  rhythmicContrast: 0.060709090107535515
  brandColors:
    - '#C5C0A3'
    - '#5E5943'
    - '#7A7764'
    - '#222B48'
    - '#FFFFCF'
github: true
layout_spectrum: 0.41897199045497885
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1a228ea-8618-411d-af36-c31a352e122a.svg
name: aaa-fo-test
navigation:
  - name: Contact
    id: 988b4968-6e9b-43cf-8a25-6452d37fcf04
    type: content
  - name: internal thing
    id: 5c742b2a-d581-4885-ac3e-83c90f395fa1
    type: content
  - name: manual link home
    url: 'https://thegrid.ai/aaa-fo-test/'
    type: external
  - name: starred post with cta
    id: 5e689cba-2211-48fd-80de-2717071563c0
    type: content
title: fo-test
content: []
description: a gridster tests gridstuff
purpose: []
