layout_spectrum: 0.6761597316687245
typography_spectrum: 0.9748845845901656
color:
  brandStrength: 0.8577965637682798
  lightness: 0.9118499469416825
  saturation: 1
  rhythmicContrast: 0.8366800887147794
  brandColors:
    - '#C5C0A3'
    - '#5E5943'
    - '#7A7764'
    - '#222B48'
    - '#FFFFCF'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1a228ea-8618-411d-af36-c31a352e122a.svg
name: aaa-fo-test
navigation:
  - name: Contact
    id: 988b4968-6e9b-43cf-8a25-6452d37fcf04
    type: content
  - name: internal thing
    id: 5c742b2a-d581-4885-ac3e-83c90f395fa1
    type: content
  - name: manual link home
    url: 'https://thegrid.ai/aaa-fo-test/'
    type: external
  - name: starred post with cta
    id: 5e689cba-2211-48fd-80de-2717071563c0
    type: content
title: fo-test
content: []
description: a gridster tests gridstuff
purpose: []
