typography_spectrum: 0.5154134910553694
color:
  brandStrength: 0.9840874471701682
  lightness: 0.1958461245521903
  saturation: 0.10906764748506248
  rhythmicContrast: 0.307705030310899
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
layout_spectrum: 0.4251432807650417
name: aaa-fo-test
navigation:
  - name: Contact
    id: 988b4968-6e9b-43cf-8a25-6452d37fcf04
    type: content
  - name: internal thing
    id: 5c742b2a-d581-4885-ac3e-83c90f395fa1
    type: content
  - name: manual link home
    url: 'https://thegrid.ai/aaa-fo-test/'
    type: external
  - name: self
    id: b53a2fdc-ce06-43ac-9d8c-87dd30833cc6
    type: content
  - name: ed-userhtml test
    id: 6f1490b5-b41b-4ec8-a905-cf59f849d876
    type: content
title: AAA Fo's testing
description: a gridster tests gridstuff cache?
